FROM golang:1.20.2-alpine3.17 AS builder

WORKDIR /app

COPY . .

RUN go build -o app

FROM scratch

COPY --from=builder /app/app .

ENV DEBUG SERVER_HOST SERVER_PORTMY SQL_HOST MYSQL_PORT MYSQL_USERNAME MYSQL_PASSWORD MYSQL_NAME REDIS_HOST REDIS_PORT REDIS_PASSWORD KAKAO_API_KEY KAKAO_CLIENT_SECRET

ENTRYPOINT [ "./app" ]